insert into ADDRESS (address_id, address_street_number, city_id) values (1, '491 Stoughton Crossing', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (2, '191 Bultman Drive', 62);
insert into ADDRESS (address_id, address_street_number, city_id) values (3, '1 Mifflin Parkway', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (4, '542 Dahle Hill', 43);
insert into ADDRESS (address_id, address_street_number, city_id) values (5, '737 Talmadge Park', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (6, '718 Bobwhite Street', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (7, '4 Annamark Place', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (8, '1130 Stuart Center', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (9, '45349 Melby Park', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (10, '5 Raven Point', 79);
insert into ADDRESS (address_id, address_street_number, city_id) values (11, '8998 Becker Pass', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (12, '53 Rutledge Center', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (13, '9172 Merry Pass', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (14, '62 Ridgeway Park', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (15, '5155 Delladonna Park', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (16, '135 Everett Road', 17);
insert into ADDRESS (address_id, address_street_number, city_id) values (17, '86370 Colorado Road', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (18, '5 High Crossing Alley', 90);
insert into ADDRESS (address_id, address_street_number, city_id) values (19, '90069 Victoria Crossing', 25);
insert into ADDRESS (address_id, address_street_number, city_id) values (20, '115 Melrose Crossing', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (21, '3131 Hanson Court', 56);
insert into ADDRESS (address_id, address_street_number, city_id) values (22, '70 Clemons Place', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (23, '5832 Crest Line Avenue', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (24, '582 Westport Drive', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (25, '066 Corben Center', 22);
insert into ADDRESS (address_id, address_street_number, city_id) values (26, '75648 Red Cloud Circle', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (27, '0 American Ash Terrace', 58);
insert into ADDRESS (address_id, address_street_number, city_id) values (28, '6258 Aberg Drive', 99);
insert into ADDRESS (address_id, address_street_number, city_id) values (29, '48 Bonner Lane', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (30, '176 Vahlen Place', 39);
insert into ADDRESS (address_id, address_street_number, city_id) values (31, '87 Veith Crossing', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (32, '12 Onsgard Road', 19);
insert into ADDRESS (address_id, address_street_number, city_id) values (33, '55 Butterfield Alley', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (34, '2 Grayhawk Avenue', 53);
insert into ADDRESS (address_id, address_street_number, city_id) values (35, '17168 Heffernan Parkway', 81);
insert into ADDRESS (address_id, address_street_number, city_id) values (36, '0 Kensington Terrace', 41);
insert into ADDRESS (address_id, address_street_number, city_id) values (37, '83063 Autumn Leaf Pass', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (38, '816 Forest Run Way', 43);
insert into ADDRESS (address_id, address_street_number, city_id) values (39, '5893 Bowman Park', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (40, '1 Shopko Road', 17);
insert into ADDRESS (address_id, address_street_number, city_id) values (41, '474 Bartelt Way', 54);
insert into ADDRESS (address_id, address_street_number, city_id) values (42, '14 Di Loreto Court', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (43, '9 Buell Plaza', 63);
insert into ADDRESS (address_id, address_street_number, city_id) values (44, '21965 Forest Dale Circle', 21);
insert into ADDRESS (address_id, address_street_number, city_id) values (45, '8 Harper Plaza', 72);
insert into ADDRESS (address_id, address_street_number, city_id) values (46, '3 Quincy Junction', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (47, '06706 Summit Plaza', 65);
insert into ADDRESS (address_id, address_street_number, city_id) values (48, '4378 Northview Road', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (49, '9 Weeping Birch Junction', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (50, '1 Oneill Terrace', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (51, '2 Stang Parkway', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (52, '339 New Castle Hill', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (53, '70 Spohn Point', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (54, '94 Pond Alley', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (55, '37 Meadow Ridge Avenue', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (56, '340 Brown Plaza', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (57, '0 Mcbride Lane', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (58, '0 Valley Edge Crossing', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (59, '49 Sheridan Lane', 99);
insert into ADDRESS (address_id, address_street_number, city_id) values (60, '30 Truax Street', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (61, '588 Northland Pass', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (62, '0 Sutherland Way', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (63, '16 Summit Crossing', 15);
insert into ADDRESS (address_id, address_street_number, city_id) values (64, '11 Green Junction', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (65, '7 Gale Plaza', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (66, '251 Graceland Center', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (67, '584 Mockingbird Crossing', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (68, '95048 Glendale Park', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (69, '2596 Tennessee Center', 35);
insert into ADDRESS (address_id, address_street_number, city_id) values (70, '3105 Ronald Regan Park', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (71, '9014 Dorton Point', 27);
insert into ADDRESS (address_id, address_street_number, city_id) values (72, '40956 Emmet Pass', 76);
insert into ADDRESS (address_id, address_street_number, city_id) values (73, '17 Jana Parkway', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (74, '83093 Browning Circle', 39);
insert into ADDRESS (address_id, address_street_number, city_id) values (75, '4 Melody Drive', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (76, '89448 Doe Crossing Trail', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (77, '22016 Linden Way', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (78, '23324 Lillian Road', 72);
insert into ADDRESS (address_id, address_street_number, city_id) values (79, '41476 Merry Parkway', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (80, '4937 Kings Junction', 28);
insert into ADDRESS (address_id, address_street_number, city_id) values (81, '50 Waxwing Court', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (82, '9070 Burrows Way', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (83, '22 Stephen Way', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (84, '042 Cottonwood Pass', 5);
insert into ADDRESS (address_id, address_street_number, city_id) values (85, '8400 Toban Crossing', 35);
insert into ADDRESS (address_id, address_street_number, city_id) values (86, '3 Manley Avenue', 30);
insert into ADDRESS (address_id, address_street_number, city_id) values (87, '59 Corscot Avenue', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (88, '0 Clemons Trail', 28);
insert into ADDRESS (address_id, address_street_number, city_id) values (89, '6 Sugar Junction', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (90, '9 Goodland Junction', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (91, '7 Prairie Rose Drive', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (92, '37875 Michigan Trail', 65);
insert into ADDRESS (address_id, address_street_number, city_id) values (93, '8986 Hollow Ridge Crossing', 79);
insert into ADDRESS (address_id, address_street_number, city_id) values (94, '9 Truax Hill', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (95, '521 Basil Crossing', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (96, '6 Dakota Hill', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (97, '3 7th Road', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (98, '26318 Novick Point', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (99, '6 Northridge Park', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (100, '179 Thierer Way', 30);
insert into ADDRESS (address_id, address_street_number, city_id) values (101, '5801 Summit Street', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (102, '349 Hanson Park', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (103, '93 Nevada Circle', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (104, '6 Del Sol Road', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (105, '85213 Ruskin Junction', 11);
insert into ADDRESS (address_id, address_street_number, city_id) values (106, '048 Maywood Terrace', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (107, '6 Toban Center', 56);
insert into ADDRESS (address_id, address_street_number, city_id) values (108, '74 4th Hill', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (109, '61 Eastlawn Avenue', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (110, '74 Express Junction', 83);
insert into ADDRESS (address_id, address_street_number, city_id) values (111, '3 3rd Way', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (112, '483 Warrior Place', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (113, '1142 Daystar Place', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (114, '82824 Prairie Rose Lane', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (115, '969 Russell Crossing', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (116, '73 Sage Circle', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (117, '213 Lake View Circle', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (118, '34 Hoffman Place', 63);
insert into ADDRESS (address_id, address_street_number, city_id) values (119, '4127 Hudson Lane', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (120, '28295 Schmedeman Court', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (121, '5195 Little Fleur Place', 81);
insert into ADDRESS (address_id, address_street_number, city_id) values (122, '32 Kim Road', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (123, '37 Monica Hill', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (124, '849 Russell Parkway', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (125, '7181 Carpenter Center', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (126, '73412 Gale Parkway', 16);
insert into ADDRESS (address_id, address_street_number, city_id) values (127, '9 Farwell Junction', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (128, '78 Jay Parkway', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (129, '33470 Kinsman Alley', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (130, '5199 Lillian Trail', 41);
insert into ADDRESS (address_id, address_street_number, city_id) values (131, '564 Dapin Trail', 99);
insert into ADDRESS (address_id, address_street_number, city_id) values (132, '58 Johnson Junction', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (133, '3587 Delaware Circle', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (134, '90 South Avenue', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (135, '6810 Northridge Trail', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (136, '2 Kennedy Trail', 5);
insert into ADDRESS (address_id, address_street_number, city_id) values (137, '07292 Blackbird Drive', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (138, '388 Roth Road', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (139, '033 Duke Lane', 35);
insert into ADDRESS (address_id, address_street_number, city_id) values (140, '5 Moland Junction', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (141, '87050 Lake View Place', 32);
insert into ADDRESS (address_id, address_street_number, city_id) values (142, '097 Shoshone Place', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (143, '6 International Lane', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (144, '12 Acker Place', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (145, '25 Granby Hill', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (146, '281 Prairieview Court', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (147, '73476 Johnson Park', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (148, '9926 Colorado Street', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (149, '2 Northview Pass', 95);
insert into ADDRESS (address_id, address_street_number, city_id) values (150, '3 Alpine Lane', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (151, '6374 Granby Court', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (152, '7 Westerfield Park', 32);
insert into ADDRESS (address_id, address_street_number, city_id) values (153, '3 Dayton Drive', 27);
insert into ADDRESS (address_id, address_street_number, city_id) values (154, '4978 Forster Street', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (155, '1927 Melvin Road', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (156, '49187 Clyde Gallagher Terrace', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (157, '79797 Fairfield Pass', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (158, '8987 Lakeland Way', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (159, '4364 Dayton Crossing', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (160, '8 Fremont Court', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (161, '604 Haas Parkway', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (162, '02 Park Meadow Parkway', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (163, '586 Sherman Junction', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (164, '1 Bellgrove Plaza', 30);
insert into ADDRESS (address_id, address_street_number, city_id) values (165, '703 Reindahl Junction', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (166, '961 Stuart Crossing', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (167, '99135 Union Plaza', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (168, '00 Golf Lane', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (169, '8 Pankratz Court', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (170, '8 Crescent Oaks Road', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (171, '5219 Eastwood Center', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (172, '07 Banding Plaza', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (173, '608 Northridge Center', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (174, '67 Maryland Drive', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (175, '63295 Sunnyside Avenue', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (176, '8503 Delladonna Junction', 28);
insert into ADDRESS (address_id, address_street_number, city_id) values (177, '1171 Milwaukee Point', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (178, '126 Bellgrove Drive', 26);
insert into ADDRESS (address_id, address_street_number, city_id) values (179, '52 Express Terrace', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (180, '8 Riverside Plaza', 63);
insert into ADDRESS (address_id, address_street_number, city_id) values (181, '1 Brickson Park Place', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (182, '50567 International Street', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (183, '492 Service Center', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (184, '6 Sutteridge Parkway', 59);
insert into ADDRESS (address_id, address_street_number, city_id) values (185, '23859 Marquette Place', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (186, '08 Linden Avenue', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (187, '83555 Mayfield Street', 22);
insert into ADDRESS (address_id, address_street_number, city_id) values (188, '895 Monterey Hill', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (189, '643 Hanson Way', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (190, '0 Shoshone Alley', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (191, '61360 Sheridan Center', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (192, '2517 Golden Leaf Street', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (193, '971 Blackbird Terrace', 82);
insert into ADDRESS (address_id, address_street_number, city_id) values (194, '5 Longview Alley', 95);
insert into ADDRESS (address_id, address_street_number, city_id) values (195, '3450 Heffernan Hill', 5);
insert into ADDRESS (address_id, address_street_number, city_id) values (196, '51 Hintze Court', 25);
insert into ADDRESS (address_id, address_street_number, city_id) values (197, '0577 Kennedy Way', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (198, '8832 Mayfield Street', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (199, '6 Montana Avenue', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (200, '982 Raven Pass', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (201, '32 Duke Lane', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (202, '2 Texas Pass', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (203, '15 Blue Bill Park Junction', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (204, '8423 Canary Park', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (205, '9 Sunfield Parkway', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (206, '52095 Claremont Avenue', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (207, '636 International Way', 16);
insert into ADDRESS (address_id, address_street_number, city_id) values (208, '9 Old Gate Trail', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (209, '3 Grasskamp Road', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (210, '977 Maple Wood Parkway', 22);
insert into ADDRESS (address_id, address_street_number, city_id) values (211, '382 Hanover Drive', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (212, '37 Miller Trail', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (213, '3 Delladonna Lane', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (214, '834 Bay Lane', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (215, '45244 Dakota Pass', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (216, '949 Rieder Point', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (217, '184 Packers Circle', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (218, '98268 Almo Way', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (219, '9975 Farwell Street', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (220, '9191 Thierer Park', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (221, '86 Eastwood Circle', 58);
insert into ADDRESS (address_id, address_street_number, city_id) values (222, '87975 Forest Place', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (223, '2 South Crossing', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (224, '08 Burrows Parkway', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (225, '6 Truax Pass', 60);
insert into ADDRESS (address_id, address_street_number, city_id) values (226, '29 Calypso Hill', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (227, '0 Shelley Hill', 26);
insert into ADDRESS (address_id, address_street_number, city_id) values (228, '5468 Shoshone Alley', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (229, '263 Bayside Point', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (230, '4 High Crossing Crossing', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (231, '9252 Knutson Hill', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (232, '7 Corry Parkway', 81);
insert into ADDRESS (address_id, address_street_number, city_id) values (233, '36596 Autumn Leaf Point', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (234, '73387 Michigan Court', 39);
insert into ADDRESS (address_id, address_street_number, city_id) values (235, '78254 Bay Place', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (236, '0206 Everett Trail', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (237, '444 Coleman Lane', 54);
insert into ADDRESS (address_id, address_street_number, city_id) values (238, '18 Mccormick Avenue', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (239, '65996 Oxford Crossing', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (240, '7876 Browning Parkway', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (241, '615 Service Place', 11);
insert into ADDRESS (address_id, address_street_number, city_id) values (242, '62 Sutteridge Drive', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (243, '1 Merry Center', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (244, '97 Upham Trail', 35);
insert into ADDRESS (address_id, address_street_number, city_id) values (245, '20756 Pawling Terrace', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (246, '81260 Crowley Place', 35);
insert into ADDRESS (address_id, address_street_number, city_id) values (247, '44823 Orin Crossing', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (248, '579 Bluejay Way', 64);
insert into ADDRESS (address_id, address_street_number, city_id) values (249, '00 Anhalt Junction', 99);
insert into ADDRESS (address_id, address_street_number, city_id) values (250, '8392 Hintze Center', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (251, '939 Monument Hill', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (252, '3 Debra Alley', 83);
insert into ADDRESS (address_id, address_street_number, city_id) values (253, '74041 Redwing Lane', 62);
insert into ADDRESS (address_id, address_street_number, city_id) values (254, '002 Del Mar Road', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (255, '38 Armistice Alley', 65);
insert into ADDRESS (address_id, address_street_number, city_id) values (256, '81 Heffernan Road', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (257, '68 Trailsway Pass', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (258, '24 Birchwood Center', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (259, '41 Petterle Drive', 5);
insert into ADDRESS (address_id, address_street_number, city_id) values (260, '431 Porter Alley', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (261, '09901 Marcy Center', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (262, '8196 West Parkway', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (263, '7 Linden Road', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (264, '30 Spaight Lane', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (265, '89839 Summit Lane', 63);
insert into ADDRESS (address_id, address_street_number, city_id) values (266, '46 Farragut Plaza', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (267, '7970 Rusk Street', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (268, '27 Petterle Drive', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (269, '012 Ilene Circle', 63);
insert into ADDRESS (address_id, address_street_number, city_id) values (270, '863 Ridge Oak Circle', 76);
insert into ADDRESS (address_id, address_street_number, city_id) values (271, '86363 Summer Ridge Terrace', 64);
insert into ADDRESS (address_id, address_street_number, city_id) values (272, '89 Petterle Plaza', 11);
insert into ADDRESS (address_id, address_street_number, city_id) values (273, '466 Porter Avenue', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (274, '85 Jenifer Court', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (275, '6728 Mandrake Plaza', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (276, '759 Center Center', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (277, '0558 Fieldstone Road', 95);
insert into ADDRESS (address_id, address_street_number, city_id) values (278, '91 Commercial Lane', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (279, '3 Moland Crossing', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (280, '795 Spenser Hill', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (281, '3208 Tomscot Park', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (282, '3750 Straubel Circle', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (283, '196 Sachtjen Street', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (284, '8924 Fremont Point', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (285, '87815 Bartillon Pass', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (286, '09 Bellgrove Alley', 62);
insert into ADDRESS (address_id, address_street_number, city_id) values (287, '41 Beilfuss Crossing', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (288, '352 Ohio Road', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (289, '72991 Valley Edge Alley', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (290, '757 Meadow Ridge Court', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (291, '880 Sachtjen Court', 28);
insert into ADDRESS (address_id, address_street_number, city_id) values (292, '18 Fordem Circle', 32);
insert into ADDRESS (address_id, address_street_number, city_id) values (293, '57243 Northland Parkway', 53);
insert into ADDRESS (address_id, address_street_number, city_id) values (294, '145 Claremont Court', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (295, '9 Claremont Avenue', 43);
insert into ADDRESS (address_id, address_street_number, city_id) values (296, '628 Morningstar Place', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (297, '5335 Portage Plaza', 39);
insert into ADDRESS (address_id, address_street_number, city_id) values (298, '55 Mifflin Trail', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (299, '0 Laurel Junction', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (300, '4524 Reindahl Lane', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (301, '6675 Bowman Avenue', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (302, '00 Randy Plaza', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (303, '8106 Nelson Pass', 41);
insert into ADDRESS (address_id, address_street_number, city_id) values (304, '29593 Duke Hill', 43);
insert into ADDRESS (address_id, address_street_number, city_id) values (305, '1582 Atwood Junction', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (306, '0436 Sunnyside Way', 32);
insert into ADDRESS (address_id, address_street_number, city_id) values (307, '44 Mallard Circle', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (308, '447 Kedzie Way', 16);
insert into ADDRESS (address_id, address_street_number, city_id) values (309, '93350 East Lane', 79);
insert into ADDRESS (address_id, address_street_number, city_id) values (310, '1 Corscot Court', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (311, '2 Mcguire Junction', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (312, '46621 International Terrace', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (313, '1477 Chinook Parkway', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (314, '225 Knutson Circle', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (315, '2521 Merrick Plaza', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (316, '886 Claremont Pass', 4);
insert into ADDRESS (address_id, address_street_number, city_id) values (317, '720 Mitchell Trail', 19);
insert into ADDRESS (address_id, address_street_number, city_id) values (318, '24 Johnson Avenue', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (319, '60028 Gale Parkway', 65);
insert into ADDRESS (address_id, address_street_number, city_id) values (320, '4 Morning Circle', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (321, '87 Petterle Junction', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (322, '3 North Avenue', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (323, '70 Glendale Park', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (324, '4438 Barby Plaza', 54);
insert into ADDRESS (address_id, address_street_number, city_id) values (325, '4873 Ridge Oak Trail', 28);
insert into ADDRESS (address_id, address_street_number, city_id) values (326, '0368 Lakewood Way', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (327, '26 Pine View Junction', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (328, '05 Fieldstone Point', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (329, '35625 Dwight Center', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (330, '921 Sugar Crossing', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (331, '08272 Anthes Pass', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (332, '2 Prentice Hill', 11);
insert into ADDRESS (address_id, address_street_number, city_id) values (333, '2539 Killdeer Circle', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (334, '2 Novick Lane', 56);
insert into ADDRESS (address_id, address_street_number, city_id) values (335, '540 Scoville Point', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (336, '1385 Continental Point', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (337, '487 Meadow Valley Parkway', 3);
insert into ADDRESS (address_id, address_street_number, city_id) values (338, '49 Barnett Avenue', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (339, '34018 Upham Crossing', 17);
insert into ADDRESS (address_id, address_street_number, city_id) values (340, '5127 Cottonwood Road', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (341, '6202 Anderson Crossing', 58);
insert into ADDRESS (address_id, address_street_number, city_id) values (342, '67 Ilene Drive', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (343, '46 Mendota Crossing', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (344, '1176 1st Circle', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (345, '78827 Bowman Plaza', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (346, '58 Nevada Pass', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (347, '752 Hovde Trail', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (348, '573 Prairieview Trail', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (349, '17 Mcguire Trail', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (350, '6601 Almo Lane', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (351, '83963 Algoma Point', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (352, '989 Arapahoe Drive', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (353, '873 Harbort Drive', 83);
insert into ADDRESS (address_id, address_street_number, city_id) values (354, '27 Chinook Junction', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (355, '5130 Logan Pass', 56);
insert into ADDRESS (address_id, address_street_number, city_id) values (356, '4257 Meadow Vale Way', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (357, '6 Fuller Avenue', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (358, '6186 Springs Park', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (359, '09391 Toban Way', 11);
insert into ADDRESS (address_id, address_street_number, city_id) values (360, '9112 Logan Hill', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (361, '7 Grim Lane', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (362, '7959 Commercial Pass', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (363, '15 Marcy Center', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (364, '991 Sutteridge Alley', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (365, '68 Texas Alley', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (366, '35 Bunker Hill Road', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (367, '845 Sage Road', 96);
insert into ADDRESS (address_id, address_street_number, city_id) values (368, '1 New Castle Street', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (369, '6 Bellgrove Alley', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (370, '13 Becker Center', 53);
insert into ADDRESS (address_id, address_street_number, city_id) values (371, '27711 Derek Plaza', 38);
insert into ADDRESS (address_id, address_street_number, city_id) values (372, '485 Stang Park', 83);
insert into ADDRESS (address_id, address_street_number, city_id) values (373, '0022 Browning Avenue', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (374, '415 Algoma Point', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (375, '26362 South Pass', 39);
insert into ADDRESS (address_id, address_street_number, city_id) values (376, '1305 Nevada Alley', 76);
insert into ADDRESS (address_id, address_street_number, city_id) values (377, '10617 Sutherland Junction', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (378, '4099 Thackeray Park', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (379, '622 Jay Trail', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (380, '1 Oxford Hill', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (381, '04907 Crowley Parkway', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (382, '519 Norway Maple Terrace', 91);
insert into ADDRESS (address_id, address_street_number, city_id) values (383, '585 Maywood Junction', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (384, '25704 Prentice Circle', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (385, '9272 Artisan Circle', 4);
insert into ADDRESS (address_id, address_street_number, city_id) values (386, '5 Village Place', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (387, '23 Northridge Court', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (388, '3 6th Lane', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (389, '15 Delaware Drive', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (390, '36329 Mitchell Lane', 57);
insert into ADDRESS (address_id, address_street_number, city_id) values (391, '1 Clarendon Parkway', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (392, '86713 Shelley Place', 84);
insert into ADDRESS (address_id, address_street_number, city_id) values (393, '00077 Stephen Park', 16);
insert into ADDRESS (address_id, address_street_number, city_id) values (394, '9834 Vera Place', 50);
insert into ADDRESS (address_id, address_street_number, city_id) values (395, '8 Northport Terrace', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (396, '9 Mandrake Junction', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (397, '37 Bultman Road', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (398, '0 Pierstorff Center', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (399, '6898 Menomonie Point', 4);
insert into ADDRESS (address_id, address_street_number, city_id) values (400, '96 Lerdahl Trail', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (401, '5398 Meadow Vale Drive', 16);
insert into ADDRESS (address_id, address_street_number, city_id) values (402, '5344 Messerschmidt Point', 72);
insert into ADDRESS (address_id, address_street_number, city_id) values (403, '01863 Oriole Lane', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (404, '10 Florence Lane', 83);
insert into ADDRESS (address_id, address_street_number, city_id) values (405, '21 Ridgeway Drive', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (406, '054 Texas Pass', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (407, '712 Brown Alley', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (408, '4565 La Follette Terrace', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (409, '38479 Drewry Place', 41);
insert into ADDRESS (address_id, address_street_number, city_id) values (410, '55 Morning Terrace', 60);
insert into ADDRESS (address_id, address_street_number, city_id) values (411, '74 Jackson Court', 64);
insert into ADDRESS (address_id, address_street_number, city_id) values (412, '3 Transport Point', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (413, '15 Cody Junction', 40);
insert into ADDRESS (address_id, address_street_number, city_id) values (414, '1 Warner Plaza', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (415, '675 Troy Crossing', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (416, '86828 Vera Crossing', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (417, '43 2nd Crossing', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (418, '3 Del Sol Avenue', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (419, '20629 Springview Crossing', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (420, '239 Rigney Pass', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (421, '5 Raven Plaza', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (422, '4 Stephen Terrace', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (423, '3 Transport Center', 79);
insert into ADDRESS (address_id, address_street_number, city_id) values (424, '987 Aberg Hill', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (425, '3344 Drewry Court', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (426, '975 Laurel Pass', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (427, '61631 Utah Pass', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (428, '83116 Old Gate Pass', 64);
insert into ADDRESS (address_id, address_street_number, city_id) values (429, '208 Rieder Circle', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (430, '96057 Dovetail Terrace', 32);
insert into ADDRESS (address_id, address_street_number, city_id) values (431, '2 Esch Avenue', 60);
insert into ADDRESS (address_id, address_street_number, city_id) values (432, '3772 Hallows Hill', 90);
insert into ADDRESS (address_id, address_street_number, city_id) values (433, '016 Moose Place', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (434, '7 Lawn Lane', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (435, '251 Vera Avenue', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (436, '24696 Corben Hill', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (437, '472 Hagan Trail', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (438, '0 Surrey Plaza', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (439, '9616 School Alley', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (440, '94927 Heffernan Place', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (441, '41 Roth Parkway', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (442, '14782 Dawn Avenue', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (443, '52 Johnson Pass', 17);
insert into ADDRESS (address_id, address_street_number, city_id) values (444, '8024 Butterfield Trail', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (445, '4 Evergreen Plaza', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (446, '836 Hallows Court', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (447, '4 Weeping Birch Trail', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (448, '60348 Luster Drive', 82);
insert into ADDRESS (address_id, address_street_number, city_id) values (449, '1243 Buell Plaza', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (450, '19509 Lakewood Alley', 97);
insert into ADDRESS (address_id, address_street_number, city_id) values (451, '637 Novick Way', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (452, '5 Hooker Pass', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (453, '8725 Thompson Hill', 66);
insert into ADDRESS (address_id, address_street_number, city_id) values (454, '01 Ridge Oak Drive', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (455, '00 Coolidge Trail', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (456, '09 Johnson Place', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (457, '95 Nancy Avenue', 27);
insert into ADDRESS (address_id, address_street_number, city_id) values (458, '50 Fremont Circle', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (459, '60 Veith Lane', 71);
insert into ADDRESS (address_id, address_street_number, city_id) values (460, '2 Summerview Way', 91);
insert into ADDRESS (address_id, address_street_number, city_id) values (461, '25914 Washington Lane', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (462, '1 Browning Lane', 21);
insert into ADDRESS (address_id, address_street_number, city_id) values (463, '83 Buell Place', 42);
insert into ADDRESS (address_id, address_street_number, city_id) values (464, '7 Di Loreto Street', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (465, '0 Bellgrove Place', 67);
insert into ADDRESS (address_id, address_street_number, city_id) values (466, '8309 Pine View Alley', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (467, '04 Straubel Trail', 26);
insert into ADDRESS (address_id, address_street_number, city_id) values (468, '5 Old Shore Hill', 53);
insert into ADDRESS (address_id, address_street_number, city_id) values (469, '36974 Ronald Regan Point', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (470, '078 Sloan Place', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (471, '76470 Kedzie Park', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (472, '35 Maple Circle', 26);
insert into ADDRESS (address_id, address_street_number, city_id) values (473, '3 Jenifer Court', 59);
insert into ADDRESS (address_id, address_street_number, city_id) values (474, '13 Mcguire Way', 29);
insert into ADDRESS (address_id, address_street_number, city_id) values (475, '911 Fallview Point', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (476, '04 Marquette Point', 1);
insert into ADDRESS (address_id, address_street_number, city_id) values (477, '9128 Randy Street', 15);
insert into ADDRESS (address_id, address_street_number, city_id) values (478, '317 Northwestern Avenue', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (479, '5 Lindbergh Street', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (480, '6739 Schlimgen Crossing', 2);
insert into ADDRESS (address_id, address_street_number, city_id) values (481, '37 Briar Crest Lane', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (482, '43248 Orin Hill', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (483, '733 Shasta Avenue', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (484, '0194 Schiller Center', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (485, '4148 Dorton Pass', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (486, '165 Cardinal Parkway', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (487, '65 Nevada Terrace', 5);
insert into ADDRESS (address_id, address_street_number, city_id) values (488, '7666 Stoughton Crossing', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (489, '16314 Bowman Court', 95);
insert into ADDRESS (address_id, address_street_number, city_id) values (490, '12609 Service Pass', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (491, '326 Barnett Junction', 91);
insert into ADDRESS (address_id, address_street_number, city_id) values (492, '9 Heffernan Crossing', 100);
insert into ADDRESS (address_id, address_street_number, city_id) values (493, '4 Service Terrace', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (494, '5848 John Wall Circle', 6);
insert into ADDRESS (address_id, address_street_number, city_id) values (495, '79 Melvin Park', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (496, '185 Atwood Avenue', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (497, '0 Del Sol Center', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (498, '03 Londonderry Avenue', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (499, '55 Valley Edge Park', 72);
insert into ADDRESS (address_id, address_street_number, city_id) values (500, '20 Trailsway Terrace', 10);
