insert into ADDRESS (address_id, address_street_number, city_id) values (1, '9 Northland Parkway', 59);
insert into ADDRESS (address_id, address_street_number, city_id) values (2, '20538 Hollow Ridge Plaza', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (3, '78 Paget Drive', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (4, '32 Beilfuss Plaza', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (5, '39686 Brickson Park Park', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (6, '97 Eggendart Point', 25);
insert into ADDRESS (address_id, address_street_number, city_id) values (7, '8662 Arapahoe Alley', 62);
insert into ADDRESS (address_id, address_street_number, city_id) values (8, '1946 Loftsgordon Hill', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (9, '92078 Dawn Lane', 31);
insert into ADDRESS (address_id, address_street_number, city_id) values (10, '39074 Dryden Park', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (11, '8027 Beilfuss Way', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (12, '683 Forest Run Park', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (13, '9 Evergreen Street', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (14, '1168 Riverside Plaza', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (15, '503 Melvin Center', 33);
insert into ADDRESS (address_id, address_street_number, city_id) values (16, '7124 Butterfield Way', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (17, '6 Gulseth Junction', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (18, '19128 Rigney Court', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (19, '82 Morningstar Terrace', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (20, '2270 Cascade Drive', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (21, '235 Garrison Road', 85);
insert into ADDRESS (address_id, address_street_number, city_id) values (22, '6300 Eastwood Road', 88);
insert into ADDRESS (address_id, address_street_number, city_id) values (23, '5 7th Alley', 89);
insert into ADDRESS (address_id, address_street_number, city_id) values (24, '4 Chinook Point', 62);
insert into ADDRESS (address_id, address_street_number, city_id) values (25, '57 Brown Point', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (26, '435 Reindahl Place', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (27, '12 Graedel Circle', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (28, '911 Nova Circle', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (29, '90 Heath Road', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (30, '423 Orin Place', 4);
insert into ADDRESS (address_id, address_street_number, city_id) values (31, '1 Birchwood Point', 78);
insert into ADDRESS (address_id, address_street_number, city_id) values (32, '0075 Cottonwood Crossing', 19);
insert into ADDRESS (address_id, address_street_number, city_id) values (33, '68826 Di Loreto Road', 68);
insert into ADDRESS (address_id, address_street_number, city_id) values (34, '6 Montana Junction', 64);
insert into ADDRESS (address_id, address_street_number, city_id) values (35, '12247 Paget Street', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (36, '8 5th Point', 59);
insert into ADDRESS (address_id, address_street_number, city_id) values (37, '8 Spenser Alley', 27);
insert into ADDRESS (address_id, address_street_number, city_id) values (38, '9 Burning Wood Street', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (39, '3749 Graedel Avenue', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (40, '9 East Point', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (41, '8 Tomscot Hill', 51);
insert into ADDRESS (address_id, address_street_number, city_id) values (42, '48 Myrtle Circle', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (43, '221 Basil Lane', 49);
insert into ADDRESS (address_id, address_street_number, city_id) values (44, '940 Bultman Lane', 96);
insert into ADDRESS (address_id, address_street_number, city_id) values (45, '160 Bartelt Center', 34);
insert into ADDRESS (address_id, address_street_number, city_id) values (46, '40 Merry Court', 92);
insert into ADDRESS (address_id, address_street_number, city_id) values (47, '63831 Nova Junction', 91);
insert into ADDRESS (address_id, address_street_number, city_id) values (48, '7 Sommers Court', 61);
insert into ADDRESS (address_id, address_street_number, city_id) values (49, '3 Lunder Lane', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (50, '08 Cody Terrace', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (51, '4645 Merry Terrace', 55);
insert into ADDRESS (address_id, address_street_number, city_id) values (52, '997 Valley Edge Plaza', 74);
insert into ADDRESS (address_id, address_street_number, city_id) values (53, '7954 Jenifer Avenue', 10);
insert into ADDRESS (address_id, address_street_number, city_id) values (54, '483 Southridge Street', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (55, '342 Valley Edge Plaza', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (56, '53496 Division Park', 69);
insert into ADDRESS (address_id, address_street_number, city_id) values (57, '1 Mariners Cove Alley', 87);
insert into ADDRESS (address_id, address_street_number, city_id) values (58, '523 Ruskin Trail', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (59, '44261 Prentice Street', 76);
insert into ADDRESS (address_id, address_street_number, city_id) values (60, '0874 Northview Drive', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (61, '6 Washington Terrace', 23);
insert into ADDRESS (address_id, address_street_number, city_id) values (62, '80068 Golf Course Trail', 77);
insert into ADDRESS (address_id, address_street_number, city_id) values (63, '98 Susan Hill', 36);
insert into ADDRESS (address_id, address_street_number, city_id) values (64, '74 Ilene Road', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (65, '849 Oxford Park', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (66, '5846 Browning Park', 52);
insert into ADDRESS (address_id, address_street_number, city_id) values (67, '5522 Spenser Crossing', 46);
insert into ADDRESS (address_id, address_street_number, city_id) values (68, '1 Manitowish Circle', 98);
insert into ADDRESS (address_id, address_street_number, city_id) values (69, '71 Forest Road', 20);
insert into ADDRESS (address_id, address_street_number, city_id) values (70, '3 Warrior Park', 86);
insert into ADDRESS (address_id, address_street_number, city_id) values (71, '4 Pearson Way', 19);
insert into ADDRESS (address_id, address_street_number, city_id) values (72, '0668 Amoth Junction', 75);
insert into ADDRESS (address_id, address_street_number, city_id) values (73, '925 Thompson Junction', 59);
insert into ADDRESS (address_id, address_street_number, city_id) values (74, '69732 Fairfield Street', 48);
insert into ADDRESS (address_id, address_street_number, city_id) values (75, '22654 Welch Lane', 96);
insert into ADDRESS (address_id, address_street_number, city_id) values (76, '87499 Fairview Road', 13);
insert into ADDRESS (address_id, address_street_number, city_id) values (77, '1 Sauthoff Crossing', 8);
insert into ADDRESS (address_id, address_street_number, city_id) values (78, '3419 Bobwhite Trail', 94);
insert into ADDRESS (address_id, address_street_number, city_id) values (79, '1926 Delaware Place', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (80, '2132 Haas Road', 19);
insert into ADDRESS (address_id, address_street_number, city_id) values (81, '0 Mendota Pass', 37);
insert into ADDRESS (address_id, address_street_number, city_id) values (82, '1907 Buell Hill', 7);
insert into ADDRESS (address_id, address_street_number, city_id) values (83, '5 Westerfield Road', 73);
insert into ADDRESS (address_id, address_street_number, city_id) values (84, '9122 Golf View Lane', 24);
insert into ADDRESS (address_id, address_street_number, city_id) values (85, '793 Karstens Place', 41);
insert into ADDRESS (address_id, address_street_number, city_id) values (86, '25773 Mosinee Terrace', 9);
insert into ADDRESS (address_id, address_street_number, city_id) values (87, '9449 Fulton Hill', 65);
insert into ADDRESS (address_id, address_street_number, city_id) values (88, '0 Meadow Valley Crossing', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (89, '02 Anniversary Road', 96);
insert into ADDRESS (address_id, address_street_number, city_id) values (90, '96 Brentwood Lane', 47);
insert into ADDRESS (address_id, address_street_number, city_id) values (91, '3231 Garrison Junction', 30);
insert into ADDRESS (address_id, address_street_number, city_id) values (92, '30 Elgar Crossing', 14);
insert into ADDRESS (address_id, address_street_number, city_id) values (93, '82911 Oneill Place', 70);
insert into ADDRESS (address_id, address_street_number, city_id) values (94, '14746 Crescent Oaks Hill', 44);
insert into ADDRESS (address_id, address_street_number, city_id) values (95, '794 Briar Crest Trail', 93);
insert into ADDRESS (address_id, address_street_number, city_id) values (96, '088 Mccormick Street', 80);
insert into ADDRESS (address_id, address_street_number, city_id) values (97, '5298 Twin Pines Alley', 18);
insert into ADDRESS (address_id, address_street_number, city_id) values (98, '192 Prairieview Crossing', 12);
insert into ADDRESS (address_id, address_street_number, city_id) values (99, '1860 Florence Alley', 45);
insert into ADDRESS (address_id, address_street_number, city_id) values (100, '06 Huxley Court', 65);
