insert into CITY (city_id, city_name, country_id) values (1, 'Mikhnëvo', 10);
insert into CITY (city_id, city_name, country_id) values (2, 'Volkhov', 14);
insert into CITY (city_id, city_name, country_id) values (3, 'Aragarças', 4);
insert into CITY (city_id, city_name, country_id) values (4, 'Quixadá', 10);
insert into CITY (city_id, city_name, country_id) values (5, 'Montalvão', 12);
insert into CITY (city_id, city_name, country_id) values (6, 'Laxey', 1);
insert into CITY (city_id, city_name, country_id) values (7, 'Budagovo', 13);
insert into CITY (city_id, city_name, country_id) values (8, 'El Salitre', 11);
insert into CITY (city_id, city_name, country_id) values (9, 'Dayeuhluhur', 5);
insert into CITY (city_id, city_name, country_id) values (10, 'Vespasiano', 2);
insert into CITY (city_id, city_name, country_id) values (11, 'Berat', 3);
insert into CITY (city_id, city_name, country_id) values (12, 'Naushahro Fīroz', 17);
insert into CITY (city_id, city_name, country_id) values (13, 'Guangyuan', 10);
insert into CITY (city_id, city_name, country_id) values (14, 'Puqi', 17);
insert into CITY (city_id, city_name, country_id) values (15, 'Laixi', 14);
insert into CITY (city_id, city_name, country_id) values (16, 'Vysokogornyy', 13);
insert into CITY (city_id, city_name, country_id) values (17, 'København', 11);
insert into CITY (city_id, city_name, country_id) values (18, 'Louka', 18);
insert into CITY (city_id, city_name, country_id) values (19, 'Bakungan', 2);
insert into CITY (city_id, city_name, country_id) values (20, 'Kalpin', 15);
insert into CITY (city_id, city_name, country_id) values (21, 'Dvorichna', 12);
insert into CITY (city_id, city_name, country_id) values (22, 'Oulad Frej', 3);
insert into CITY (city_id, city_name, country_id) values (23, 'Sembabule', 18);
insert into CITY (city_id, city_name, country_id) values (24, 'Dniprovka', 14);
insert into CITY (city_id, city_name, country_id) values (25, 'Khalīlābād', 3);
insert into CITY (city_id, city_name, country_id) values (26, 'Serang', 11);
insert into CITY (city_id, city_name, country_id) values (27, 'Debre Tabor', 17);
insert into CITY (city_id, city_name, country_id) values (28, 'Kiangan', 10);
insert into CITY (city_id, city_name, country_id) values (29, 'Łaskarzew', 16);
insert into CITY (city_id, city_name, country_id) values (30, 'Świnice Warckie', 20);
insert into CITY (city_id, city_name, country_id) values (31, 'Mojo', 1);
insert into CITY (city_id, city_name, country_id) values (32, 'Zhuangta', 7);
insert into CITY (city_id, city_name, country_id) values (33, 'Solnice', 19);
insert into CITY (city_id, city_name, country_id) values (34, 'Azara', 13);
insert into CITY (city_id, city_name, country_id) values (35, 'Washington', 8);
insert into CITY (city_id, city_name, country_id) values (36, 'Aparecida', 16);
insert into CITY (city_id, city_name, country_id) values (37, 'San Marcos', 0);
insert into CITY (city_id, city_name, country_id) values (38, 'Beauvais', 16);
insert into CITY (city_id, city_name, country_id) values (39, 'Lingqiao', 8);
insert into CITY (city_id, city_name, country_id) values (40, 'Dargaz', 12);
insert into CITY (city_id, city_name, country_id) values (41, 'Santa Rita Village', 16);
insert into CITY (city_id, city_name, country_id) values (42, 'Banjar Buahan', 3);
insert into CITY (city_id, city_name, country_id) values (43, 'Orsha', 8);
insert into CITY (city_id, city_name, country_id) values (44, 'Quimilí', 19);
insert into CITY (city_id, city_name, country_id) values (45, 'Lexington', 18);
insert into CITY (city_id, city_name, country_id) values (46, 'Villa Concepción del Tío', 17);
insert into CITY (city_id, city_name, country_id) values (47, 'Ambulong', 1);
insert into CITY (city_id, city_name, country_id) values (48, 'Sambonggede', 4);
insert into CITY (city_id, city_name, country_id) values (49, 'Cintra', 20);
insert into CITY (city_id, city_name, country_id) values (50, 'Ballinroad', 0);
insert into CITY (city_id, city_name, country_id) values (51, 'Rushanzhai', 19);
insert into CITY (city_id, city_name, country_id) values (52, 'Santa Barbara', 17);
insert into CITY (city_id, city_name, country_id) values (53, 'Ya‘bad', 11);
insert into CITY (city_id, city_name, country_id) values (54, 'Arnage', 1);
insert into CITY (city_id, city_name, country_id) values (55, 'Triandría', 8);
insert into CITY (city_id, city_name, country_id) values (56, 'Pelabuhan Dagang', 8);
insert into CITY (city_id, city_name, country_id) values (57, 'Cambuga', 5);
insert into CITY (city_id, city_name, country_id) values (58, 'Pagangan', 4);
insert into CITY (city_id, city_name, country_id) values (59, 'Tākestān', 15);
insert into CITY (city_id, city_name, country_id) values (60, 'Porta', 13);
insert into CITY (city_id, city_name, country_id) values (61, 'Murun-kuren', 14);
insert into CITY (city_id, city_name, country_id) values (62, 'Otavalo', 3);
insert into CITY (city_id, city_name, country_id) values (63, 'Seka', 12);
insert into CITY (city_id, city_name, country_id) values (64, 'Ledeč nad Sázavou', 18);
insert into CITY (city_id, city_name, country_id) values (65, 'La Cruz', 3);
insert into CITY (city_id, city_name, country_id) values (66, 'Satte', 16);
insert into CITY (city_id, city_name, country_id) values (67, 'Pyshchug', 19);
insert into CITY (city_id, city_name, country_id) values (68, 'Simrishamn', 3);
insert into CITY (city_id, city_name, country_id) values (69, 'Dunaújváros', 8);
insert into CITY (city_id, city_name, country_id) values (70, 'Kuncen', 15);
insert into CITY (city_id, city_name, country_id) values (71, 'Yasynuvata', 6);
insert into CITY (city_id, city_name, country_id) values (72, 'Leigongmiao', 9);
insert into CITY (city_id, city_name, country_id) values (73, 'Motala', 16);
insert into CITY (city_id, city_name, country_id) values (74, 'Almada', 14);
insert into CITY (city_id, city_name, country_id) values (75, 'Eskilstuna', 10);
insert into CITY (city_id, city_name, country_id) values (76, 'Colesberg', 17);
insert into CITY (city_id, city_name, country_id) values (77, 'Antaparco', 18);
insert into CITY (city_id, city_name, country_id) values (78, 'Boisbriand', 13);
insert into CITY (city_id, city_name, country_id) values (79, 'Mainri', 0);
insert into CITY (city_id, city_name, country_id) values (80, 'Antanhol', 4);
insert into CITY (city_id, city_name, country_id) values (81, 'Mombaça', 20);
insert into CITY (city_id, city_name, country_id) values (82, 'Kowale', 19);
insert into CITY (city_id, city_name, country_id) values (83, 'Menanga', 11);
insert into CITY (city_id, city_name, country_id) values (84, 'Banqiao', 13);
insert into CITY (city_id, city_name, country_id) values (85, 'Sindon', 18);
insert into CITY (city_id, city_name, country_id) values (86, 'Vilares', 12);
insert into CITY (city_id, city_name, country_id) values (87, 'Kushima', 20);
insert into CITY (city_id, city_name, country_id) values (88, 'Jinyuan', 13);
insert into CITY (city_id, city_name, country_id) values (89, 'Doug An', 9);
insert into CITY (city_id, city_name, country_id) values (90, 'Gongxi', 8);
insert into CITY (city_id, city_name, country_id) values (91, 'Pandan Niog', 18);
insert into CITY (city_id, city_name, country_id) values (92, 'Segbwema', 5);
insert into CITY (city_id, city_name, country_id) values (93, 'Changqing', 4);
insert into CITY (city_id, city_name, country_id) values (94, 'Jepat Kidul', 16);
insert into CITY (city_id, city_name, country_id) values (95, 'Macaé', 3);
insert into CITY (city_id, city_name, country_id) values (96, 'Tenjolaya', 10);
insert into CITY (city_id, city_name, country_id) values (97, 'Xiamayu', 12);
insert into CITY (city_id, city_name, country_id) values (98, 'Jimaguayú', 8);
insert into CITY (city_id, city_name, country_id) values (99, 'Tangzhai', 11);
insert into CITY (city_id, city_name, country_id) values (100, 'Uva', 4);
