insert into DEPARTMENT (dept_id, dept_name) values (1, 'DECK');
insert into DEPARTMENT (dept_id, dept_name) values (2, 'ENGINEERING');
insert into DEPARTMENT (dept_id, dept_name) values (3, 'GALLEY');
insert into DEPARTMENT (dept_id, dept_name) values (4, 'FOOD AND BEVERAGE');
insert into DEPARTMENT (dept_id, dept_name) values (5, 'HOUSEKEEPING');
insert into DEPARTMENT (dept_id, dept_name) values (6, 'SHOPPING');
insert into DEPARTMENT (dept_id, dept_name) values (7, 'IT');
insert into DEPARTMENT (dept_id, dept_name) values (8, 'MEDICAL');
insert into DEPARTMENT (dept_id, dept_name) values (9, 'SECURITY');
insert into DEPARTMENT (dept_id, dept_name) values (10, 'ENTERTAINMENT');
