insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (1, 'Guiness', 2.01, 304, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (2, 'Asahi', 21.33, 247, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (3, 'Sapporo', 32.41, 114, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (4, 'Corona', 10.74, 30, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (5, 'Heineken', 20.43, 255, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (6, 'Stella Artios', 18.77, 118, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (7, 'Jack Daniels', 13.83, 434, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (8, 'Johnny Walker Black', 10.62, 249, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (9, 'Jameson', 28.39, 464, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (10, 'Grey Goose', 19.71, 164, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (11, 'Smirnoff', 16.61, 440, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (12, 'Crown Royal', 8.35, 54, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (13, 'Budweiser', 26.02, 232, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (14, 'Water', 25.66, 353, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (15, 'Captain Morgan', 9.97, 167, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (16, 'Pabst Blue Ribbon', 37.8, 229, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (17, 'Tsing Tsao', 43.48, 5, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (18, 'Baiju', 30.48, 325, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (19, 'Moonshine', 16.74, 363, 1);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (20, 'literally just pure alcohol', 3.29, 48, 1);

insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (21, 'Guiness', 2.01, 304, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (22, 'Asahi', 21.33, 247, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (23, 'Sapporo', 32.41, 114, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (24, 'Corona', 10.74, 30, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (25, 'Heineken', 20.43, 255, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (26, 'Stella Artios', 18.77, 118, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (27, 'Jack Daniels', 13.83, 434, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (28, 'Johnny Walker Black', 10.62, 249, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (29, 'Jameson', 28.39, 464, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (30, 'Grey Goose', 19.71, 164, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (31, 'Smirnoff', 16.61, 440, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (32, 'Crown Royal', 8.35, 54, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (33, 'Budweiser', 26.02, 232, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (34, 'Water', 25.66, 353, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (35, 'Captain Morgan', 9.97, 167, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (36, 'Pabst Blue Ribbon', 37.8, 229, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (37, 'Tsing Tsao', 43.48, 5, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (38, 'Baiju', 30.48, 325, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (39, 'Moonshine', 16.74, 363, 2);
insert into DRINKS (drink_id, drink_name, drink_price, drink_inventory, ship_id) values (40, 'literally just pure alcohol', 3.29, 48, 2);