insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (1, 'Pen', 8.49, 121, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (2, 'Shirt', 24.74, 294, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (3, 'Necktie', 31.17, 429, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (4, 'Hat', 45.49, 391, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (5, 'Shoes', 15.1, 96, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (6, 'Dress', 8.37, 120, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (7, 'Stuffed Animal', 42.3, 169, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (8, 'Gloves', 19.15, 172, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (9, 'Sunglasses', 16.23, 137, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (10, 'High Heels', 45.73, 278, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (11, 'Wrist Watch', 5.03, 130, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (12, 'Yam', 44.45, 189, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (13, 'Coffee Mug', 3.39, 49, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (14, 'Shot Glass', 44.07, 128, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (15, 'Poster', 14.1, 263, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (16, 'Notepad', 45.87, 51, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (17, 'Lightbulb', 6.95, 441, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (18, 'Toothbrush', 36.47, 200, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (19, 'Water Bottle', 31.65, 4, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (20, 'Knife', 29.68, 460, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (21, 'Pants', 17.33, 113, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (22, 'Tesla Model X', 42.84, 145, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (23, 'Imperial II-class Star Destroyer', 29.84, 475, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (24, 'Combine Harvester', 49.48, 50, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (25, 'A Jar of Pickles', 25.01, 123, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (26, 'Sweater', 8.93, 198, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (27, 'Minuteman III ICBM', 37.76, 365, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (28, 'nVidia GeForce GTX 980Ti', 34.64, 473, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (29, 'Apples', 8.3, 173, 1);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (30, 'Indestructable Bucket', 3.45, 446, 1);
