insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (31, 'Pen', 8.49, 121, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (32, 'Shirt', 24.74, 294, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (33, 'Necktie', 31.17, 429, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (34, 'Hat', 45.49, 391, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (35, 'Shoes', 15.1, 96, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (36, 'Dress', 8.37, 120, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (37, 'Stuffed Animal', 42.3, 169, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (38, 'Gloves', 19.15, 172, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (39, 'Sunglasses', 16.23, 137, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (40, 'High Heels', 45.73, 278, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (41, 'Wrist Watch', 5.03, 130, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (42, 'Yam', 44.45, 189, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (43, 'Coffee Mug', 3.39, 49, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (44, 'Shot Glass', 44.07, 128, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (45, 'Poster', 14.1, 263, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (46, 'Notepad', 45.87, 51, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (47, 'Lightbulb', 6.95, 441, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (48, 'Toothbrush', 36.47, 200, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (49, 'Water Bottle', 31.65, 4, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (50, 'Knife', 29.68, 460, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (51, 'Pants', 17.33, 113, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (52, 'Tesla Model X', 42.84, 145, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (53, 'Imperial II-class Star Destroyer', 29.84, 475, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (54, 'Combine Harvester', 49.48, 50, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (55, 'A Jar of Pickles', 25.01, 123, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (56, 'Sweater', 8.93, 198, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (57, 'Minuteman III ICBM', 37.76, 365, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (58, 'nVidia GeForce GTX 980Ti', 34.64, 473, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (59, 'Apples', 8.3, 173, 2);
insert into GIFTS (gift_id, gift_name, gift_price, gift_inventory, ship_id) values (60, 'Indestructable Bucket', 3.45, 446, 2);
