insert into JOBS (job_id, job_title, dept_id) values (1, 'Captain', 1);
insert into JOBS (job_id, job_title, dept_id) values (2, 'First Mate', 1);
insert into JOBS (job_id, job_title, dept_id) values (3, 'Helmsman', 1);
insert into JOBS (job_id, job_title, dept_id) values (4, 'Navigator', 1);
insert into JOBS (job_id, job_title, dept_id) values (5, 'Engineer', 2);
insert into JOBS (job_id, job_title, dept_id) values (6, 'Senior Engineer', 2);
insert into JOBS (job_id, job_title, dept_id) values (7, 'Master Chef', 3);
insert into JOBS (job_id, job_title, dept_id) values (8, 'Sous Chef', 3);
insert into JOBS (job_id, job_title, dept_id) values (9, 'Line Cook', 3);
insert into JOBS (job_id, job_title, dept_id) values (10, 'Server', 4);
insert into JOBS (job_id, job_title, dept_id) values (11, 'Bartender', 4);
insert into JOBS (job_id, job_title, dept_id) values (12, 'Cleaner', 5);
insert into JOBS (job_id, job_title, dept_id) values (13, 'Store Manager', 6);
insert into JOBS (job_id, job_title, dept_id) values (14, 'Cashier', 6);
insert into JOBS (job_id, job_title, dept_id) values (15, 'Help Desk', 7);
insert into JOBS (job_id, job_title, dept_id) values (16, 'Network Administrator', 7);
insert into JOBS (job_id, job_title, dept_id) values (17, 'Doctor', 8);
insert into JOBS (job_id, job_title, dept_id) values (18, 'Nurse', 8);
insert into JOBS (job_id, job_title, dept_id) values (19, 'Security Guard', 9);
insert into JOBS (job_id, job_title, dept_id) values (20, 'Hostess', 10);
