insert into PORTS (port_id, port_name, city_id) values (1, 'Cool Port', 47);
insert into PORTS (port_id, port_name, city_id) values (2, 'Neat Port', 38);
insert into PORTS (port_id, port_name, city_id) values (3, 'Bad Port', 26);
insert into PORTS (port_id, port_name, city_id) values (4, 'USB Port', 9);
insert into PORTS (port_id, port_name, city_id) values (5, 'Large Port', 6);
insert into PORTS (port_id, port_name, city_id) values (6, 'Harbour of Awesome', 41);
insert into PORTS (port_id, port_name, city_id) values (7, 'Port Coquitlam', 23);
insert into PORTS (port_id, port_name, city_id) values (8, 'Messy Port', 20);
insert into PORTS (port_id, port_name, city_id) values (9, 'HDMI Port', 12);
insert into PORTS (port_id, port_name, city_id) values (10, 'Port Harbour', 21);
insert into PORTS (port_id, port_name, city_id) values (11, 'Harbour Port', 16);
insert into PORTS (port_id, port_name, city_id) values (12, 'Port Name', 15);
insert into PORTS (port_id, port_name, city_id) values (13, 'Port of Ports', 13);
insert into PORTS (port_id, port_name, city_id) values (14, 'Port of Syntax Error', 44);
insert into PORTS (port_id, port_name, city_id) values (15, 'Harbour of Harbours', 10);
insert into PORTS (port_id, port_name, city_id) values (16, 'Boat Port', 24);
insert into PORTS (port_id, port_name, city_id) values (17, 'Mega Marina', 7);
insert into PORTS (port_id, port_name, city_id) values (18, 'Power Port', 27);
insert into PORTS (port_id, port_name, city_id) values (19, 'Port Forward', 1);
insert into PORTS (port_id, port_name, city_id) values (20, 'Harbour Ing Fuja Teevs', 32);
