insert into WORKAREAS (area_id, area_name, dept_id) values (1, 'Bridge', 1);
insert into WORKAREAS (area_id, area_name, dept_id) values (2, 'CIC', 1);
insert into WORKAREAS (area_id, area_name, dept_id) values (3, 'Engine Room One', 2);
insert into WORKAREAS (area_id, area_name, dept_id) values (4, 'Upper Deck Kitchen', 3);
insert into WORKAREAS (area_id, area_name, dept_id) values (5, 'Upper Deck Dining Area', 4);
insert into WORKAREAS (area_id, area_name, dept_id) values (6, 'Lower Deck Kitchen', 3);
insert into WORKAREAS (area_id, area_name, dept_id) values (7, 'Lower Deck Dining Area', 4);
insert into WORKAREAS (area_id, area_name, dept_id) values (8, 'Cool Gift Shop', 6);
insert into WORKAREAS (area_id, area_name, dept_id) values (9, 'Expensive Gift Shop', 6);
insert into WORKAREAS (area_id, area_name, dept_id) values (10, 'Laundry Room', 5);
insert into WORKAREAS (area_id, area_name, dept_id) values (11, 'Theatre', 10);
insert into WORKAREAS (area_id, area_name, dept_id) values (12, 'Engine Room Two', 2);
insert into WORKAREAS (area_id, area_name, dept_id) values (13, 'Frog and Nightgown Sports Bar', 4);
insert into WORKAREAS (area_id, area_name, dept_id) values (14, 'Rusty Bent Glaive Pub', 4);
insert into WORKAREAS (area_id, area_name, dept_id) values (15, 'Server Room', 7);
insert into WORKAREAS (area_id, area_name, dept_id) values (16, 'IT Help Desk', 7);
insert into WORKAREAS (area_id, area_name, dept_id) values (17, 'Upper Deck Aid Station', 8);
insert into WORKAREAS (area_id, area_name, dept_id) values (18, 'Stern Medbay', 8);
insert into WORKAREAS (area_id, area_name, dept_id) values (19, 'Security Office', 9);
insert into WORKAREAS (area_id, area_name, dept_id) values (20, 'Casino', 10);
